/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TemporizadorRouteImport } from './routes/temporizador'
import { Route as FimRouteImport } from './routes/fim'
import { Route as IndexRouteImport } from './routes/index'

const TemporizadorRoute = TemporizadorRouteImport.update({
  id: '/temporizador',
  path: '/temporizador',
  getParentRoute: () => rootRouteImport,
} as any)
const FimRoute = FimRouteImport.update({
  id: '/fim',
  path: '/fim',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fim': typeof FimRoute
  '/temporizador': typeof TemporizadorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fim': typeof FimRoute
  '/temporizador': typeof TemporizadorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/fim': typeof FimRoute
  '/temporizador': typeof TemporizadorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/fim' | '/temporizador'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/fim' | '/temporizador'
  id: '__root__' | '/' | '/fim' | '/temporizador'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FimRoute: typeof FimRoute
  TemporizadorRoute: typeof TemporizadorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/temporizador': {
      id: '/temporizador'
      path: '/temporizador'
      fullPath: '/temporizador'
      preLoaderRoute: typeof TemporizadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fim': {
      id: '/fim'
      path: '/fim'
      fullPath: '/fim'
      preLoaderRoute: typeof FimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FimRoute: FimRoute,
  TemporizadorRoute: TemporizadorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
